version: '3.9'
services:
  app:
    image: ghcr.io/shba007/unpsy-web:latest
    volumes:
      - unpsy_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4202:3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  unpsy_static:
    external: true

networks:
  front-tier:
    driver: overlay
